name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can also use macOS or Windows

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically available
          publish_dir: ./  # Root directory where index.html is located
          publish_branch: gh-pages  # The branch where your site will be deployed (usually `gh-pages`)


